version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: logitrack_postgres
    environment:
      POSTGRES_DB: logitrack
      POSTGRES_USER: logitrack_user
      POSTGRES_PASSWORD: logitrack_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logitrack_network

  redis:
    image: redis:7-alpine
    container_name: logitrack_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - logitrack_network

  adminer:
    image: adminer
    container_name: logitrack_adminer
    ports:
      - "8080:8080"
    networks:
      - logitrack_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:

networks:
  logitrack_network:
    driver: bridge
